### ISSUE TITLE
Postgres Authentication Fails

### ISSUE THREAD

**Issue by AMoonRabbit** [angristan/docker-pleroma#21]
Hello,

I was just working through the guide when I stumbled across an authentication issue when trying to setup the database with the following:
```docker-compose run --rm web mix ecto.migrate```

I changed the POSTGRES_PASSWORD in the docker-compose.yml, and everything from that point to now has been okay. Please can you advise?

This is the output
```
Creating network "docker-pleroma_default" with the default driver
Creating pleroma_postgres ... done

03:56:34.309 [error] Postgrex.Protocol (#PID<0.527.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "pleroma"

03:56:34.309 [error] Postgrex.Protocol (#PID<0.528.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "pleroma"

03:56:36.074 [error] Postgrex.Protocol (#PID<0.527.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "pleroma"

03:56:37.052 [error] Postgrex.Protocol (#PID<0.528.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "pleroma"

03:56:37.119 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :pleroma, Pleroma.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2919ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. By tracking down slow queries and making sure they are running fast enough
  2. Increasing the pool_size (albeit it increases resource consumption)
  3. Allow requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:686: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.4.5) lib/ecto/migrator.ex:641: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.4.5) lib/ecto/migrator.ex:484: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.4.5) lib/ecto/migrator.ex:406: Ecto.Migrator.run/4
    (ecto_sql 3.4.5) lib/ecto/migrator.ex:142: Ecto.Migrator.with_repo/3
    (pleroma 2.1.50-854-g294628d9-develop) lib/mix/tasks/pleroma/ecto/migrate.ex:63: Mix.Tasks.Pleroma.Ecto.Migrate.run/1

```

**Comment by AMoonRabbit** [comment]
I started from scratch and managed to successfully build it.

**Comment by radnor** [comment]
For anyone else experiencing this, it's probably due to changing the password in `docker-compose.yml` _after_ creating the local postgres database files. 

To fix this use the initial password, or delete the files in the `postgres` folder and start over by migrating a new database.
